### ISSUE TITLE
Overwriting the default account

### ISSUE THREAD

**Issue by aydinmirac** [SlinkyProject/slurm-bridge#1]
Dear All,

First of all, thanks for creating this awesome project. I tested it on my small test cluster, and I have a question about overwriting the default account.

In the installation steps, we create a token to communicate with the Slurm REST API:

```
export SLURM_JWT=$(scontrol token username=slurm lifespan=infinite)
```

When running a Kubernetes pod, I tried to change the default username using the provided annotation, as shown below:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-sleep-single
  namespace: slurm-bridge
  # slurm-bridge annotations on the parent object
  annotations:
    slinky.slurm.net/job-name: job-sleep-single
    slinky.slurm.net/timelimit: "5"
    # AnnotationAccount overrides the default account
    # for the Slurm placeholder job.
    # AnnotationAccount = "slinky.slurm.net/account"
    slinky.slurm.net/account: myuser
```
However, I noticed that the job started running with the username `slurm` in the SLURM queue. I expected the username to be overwritten as `myuser`. If every job is submitted with the `slurm` user, it is challenging to manage accounting on the Slurm side.

On the SLURM website, it says, `The root account, or SlurmUser account, can be used to generate tokens for any user.` That is why I thought that the token created above could be used for any user, but I am not sure.

Do you have suggestion for this issue? Or did I misconfigure something?

I appreciate your help.
